<?php require "header.php"; do_header("Blog");
class blogpost
{
    public $title;
    public $date;
    public $contents;
    public $fdate;
    public function __construct($_title,$_date,$_contents)
    {
        list($this->title,$this->date,$this->contents)=[$_title,new DateTime($_date),$_contents];
    }
}
$blogposts=[new blogpost("Bernie Sanders Stuns the Nation by Winning 90% of Delegates in New York","4/20/2016 6:31:42 AM","Bernie Sanders shocks everyone and takes the lead in delegates for the Presidential nomination.  By virtue of agressive campaigning within the state, Sanders wins 90% of delegates in his home state.  By taking 262 delegates, Sanders sends a powerful message to the American public that not only can he win, but can win big."),new blogpost("Bernie Wins Big Again","4/26/2016 8:07:42 PM","By winning all 5 states in today's primaries, Bernie Sanders has once again shown his momentum going into the 2016 election.  Winning 305 out of 392 delegates tonight, including the majority from each state, Sanders is only 732 delegates away from clinching the nomination.  Counting superdelegates, 42% of which now pledge to support Sanders, he is only 521 delegates from the nomination."),new blogpost("Bernie Sanders now Carries Half of Superdelegates","5/1/2016 5:29:23 PM","Superdelegates, Hillary Clinton's way to exaggerate her lead in the primaries, are now switching camps and Feeling the Bern.  Half of superdelegates now support Bernie Sanders.  They are starting to recognize Sanders' momentum, and this shows that Hillary's election is not as much of a shoe-in as it would seem"),new blogpost("Bernie Sanders Reaches Magic Number - Clinches Nomination","6/7/2016 11:34:39 PM","By winning California, Sanders reaches the magic number of 2,383 delegates, clinching the nomination of the Democratic National Convention.  Sanders has defied all odds and beat the establishment to win in the primaries.  Sanders will use this momentum to bring about a win in November over the eventual Republican nominee."),new blogpost("Hillary Clinton Suspends Campaign, Concedes Nomination","6/8/2016 5:31:05 PM","The first battle has officially been won - Bernie Sanders is now all but officially the Democratic Nominee, as the only active candidate to have delegates.  It is important now for the Democratic Party to come together against the Republicans.  We now have a distinct advantage - we are now more organized than the  Republicans as we are the first to decide a nominee."),
new blogpost("Bernie Sanders Chooses Hillary Clinton as Running Mate","6/9/2016 4:20:29 PM","Bernie Sanders has selected a running mate, and it is a familiar face on the campaign trail.  Bernie Sanders has asked Hillary Clinton to be his running mate in his campaign in the 2016 election.  Despite their differences, Clinton shares many of Sanders' policies and is the clear choice for a vice president.  The two candidates have 'buried the hatchet' of the primary season, and they will make a run together for the presidency."),new blogpost("Donald Trump Makes Ludicrous Claims Regarding Sanders","7/3/2016 4:07:29 PM","On the campaign trail, Donald Trump, the Republican frontrunner, has made claims that Sanders is a 'literal communist' and 'talks every day with Mao Zedong'.  These claims are not only untrue, but are completely illogical.  Firstly, Sanders has never claimed to be a communist.  He sides with socialistic principles, which are applied through the United Kingdom, France, and the rest of Europe.  Additionally, Sanders has never spoken with Zedong - in fact, he could not talk with Zedong as he has been deceased since 1976.  This is only the latest in a string of emotionally charged rhetoric coming from the Republican candidates."),new blogpost("Four Months Remain Until Election","7/8/2016 3:08:28 PM","Four months remain until the 2016 Presidential Election, and Bernie Sanders' campaign is in full swing.  In the absence of a clear opponent, Sanders is focusing his efforts on getting his message out to the general public and showing that he is an electable candidate.  If you would like to help Sanders, please consider <a href='donate.html'>donating</a> to his campaign."),new blogpost("Bernie Sanders will face Donald Trump after Close Convention","7/18/2016 10:38:29 PM","After a close convention, Donald Trump wins the Republican nomination by only 15 delegates, despite a large schism within the party.  With so less time to organize a campaign, Trump is at a severe disadvantage caused by his agressive alienation of minories.  The Democratic candidates, on the other hand, ran a positive campaign, showing the world why they were better than the other, while Republicans only sought to destroy each other.  The Sanders campaign now focuses on showing the world why he is more attractive than Trump in order to win the White House."),new blogpost("Bernie Sanders Officially Democratic Nominee","7/25/2016 7:13:05 PM","As a formality after the campaign season, Bernie Sanders is officially declared the Democratic nominee for this year's election.  The Sanders campaign now welcomes the support of the Democratic National Comittee in his effort to make a change in Washington.")];
?>
<div id="blogpost">
    <?php foreach($blogposts as $n=>$blogpost)
    {
        list($title,$date,$contents)=[$blogpost->title,$blogpost->date->format("l, F j Y - g:i A \E\D\T"),$blogpost->contents];
        echo "<h3 class=\"blogtitle\">$title</h3><h4 class=\"blogdate\">$date</h4><p class=\"blogtext\">$contents</p>";
    }?>
</div>
<?php require "footer.php";
